/**
 * CreateDataProduct handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createDataProduct } from "@unifora/api-server/domains/data-products/handlers";
import type { DataProductsDDDDependencies } from "@unifora/api-server/domains/data-products";
import { createDataProduct as createDataProductEntity } from "@unifora/factories/data-products";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@unifora/tests/shared";
import { DATAPRODUCTS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateDataProduct", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DataProductsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DataProductsDDDDependencies>(
      DATAPRODUCTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createDataProductEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateDataProduct, "execute").mockResolvedValue(useCaseResult);

    await createDataProduct(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateDataProduct.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
