/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-data-product.handler.test.js";
export * from "./get-data-product.handler.test.js";
export * from "./list-data-products.handler.test.js";
export * from "./update-data-product-steward.handler.test.js";
