/**
 * ListDataProducts handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDataProducts } from "@unifora/api-server/domains/data-products/handlers";
import type { DataProductsDDDDependencies } from "@unifora/api-server/domains/data-products";
import { createDataProduct as createDataProductEntity } from "@unifora/factories/data-products";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@unifora/tests/shared";
import { DATAPRODUCTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDataProducts", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DataProductsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DataProductsDDDDependencies>(
      DATAPRODUCTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDataProductEntity({ orgId }),
      createDataProductEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDataProducts, "execute").mockResolvedValue(useCaseResult);

    await listDataProducts(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDataProducts.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
