/**
 * Handlers for Share
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SharesDomainModule } from "../dependencies/shares-ddd.dependencies.js";
import type { CreateShareRequestInput, ListShareRequestsInput } from "@unifora/services/shares";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/shares
 * Operation: listShareRequests
 */
export async function listShareRequests(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { shareScope?: string | string[], cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: SharesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListShareRequestsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.shares.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/shares
 * Operation: createShareRequest
 */
export async function createShareRequest(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SharesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateShareRequestInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.shares.create.execute(input);
  return reply.code(201).send(result);
}


