/**
 * EscalationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escalations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EscalationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements EscalationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  EscalationRepository,
} from "@unifora/services/escalations";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { EscalationRepositoryDdb } from "./escalation-repository.ddb.js";

/**
 * EscalationRepositoryAdapter
 *
 * Implements EscalationRepository port for infrastructure layer.
 */
export class EscalationRepositoryAdapter implements EscalationRepository {
  private readonly ddb: EscalationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new EscalationRepositoryDdb(this.dynamoClient);
  }

  async listEscalations(input: Parameters<EscalationRepository['listEscalations']>[0]): Promise<Awaited<ReturnType<EscalationRepository['listEscalations']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listEscalations(input);
  }

  async openEscalation(input: Parameters<EscalationRepository['openEscalation']>[0]): Promise<Awaited<ReturnType<EscalationRepository['openEscalation']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.openEscalation(input);
  }
}
