/**
 * PipelineRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pipelines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PipelineRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PipelineRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PipelineRepository,
} from "@unifora/services/pipelines";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PipelineRepositoryDdb } from "./pipeline-repository.ddb.js";

/**
 * PipelineRepositoryAdapter
 *
 * Implements PipelineRepository port for infrastructure layer.
 */
export class PipelineRepositoryAdapter implements PipelineRepository {
  private readonly ddb: PipelineRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PipelineRepositoryDdb(this.dynamoClient);
  }

  async listPipelines(input: Parameters<PipelineRepository['listPipelines']>[0]): Promise<Awaited<ReturnType<PipelineRepository['listPipelines']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listPipelines(input);
  }

  async registerPipeline(input: Parameters<PipelineRepository['registerPipeline']>[0]): Promise<Awaited<ReturnType<PipelineRepository['registerPipeline']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerPipeline(input);
  }

  async getPipeline(input: Parameters<PipelineRepository['getPipeline']>[0]): Promise<Awaited<ReturnType<PipelineRepository['getPipeline']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getPipeline(input);
  }
}
