/**
 * GetLineage DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLineageParams } from "@unifora/core/lineage";

export function createGetLineageRequest(overrides: Partial<GetLineageParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
