/**
 * Repository interface for ProgrammePulse
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  ProgrammePulseEntity
} from "../models/programme-pulse.entity.js";
/**
 * ProgrammePulseRepository Interface
 */
export interface ProgrammePulseRepository extends ReadRepository<ProgrammePulseEntity, string, Record<string, never>> {

}
