/**
 * Repository interface for UseCase
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  UseCaseEntity
} from "../models/use-case.entity.js";
import type {
  ListUseCasesParams,
  UseCase
} from "../types/index.js";
/**
 * UseCaseRepository Interface
 */
export interface UseCaseRepository extends CreateReadRepository<UseCaseEntity, UseCase, string, ListUseCasesParams> {

}
