/**
 * Share DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Share DTOs
 *
 * DDD: Application DTOs for Share use cases.
 */

import type { CreateShareRequestRequestInput, ListShareRequestsParams } from "@unifora/core/shares/types";

export type ListShareRequestsInput = ListShareRequestsParams;

export type CreateShareRequestInput = CreateShareRequestRequestInput;

export type ListShareRequestsOutput = {};

export type CreateShareRequestOutput = {};
