/**
 * ExecuteUpdateDataProductSteward - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpdateDataProductSteward Use Case
 *
 * DDD: Application use case for update DataProduct.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpdateDataProductStewardInput, UpdateDataProductStewardOutput } from "../dto/data-product.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { DataProductRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteUpdateDataProductSteward {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataProduct: DataProductRepository
  ) {}

  async execute(input: UpdateDataProductStewardInput): Promise<UpdateDataProductStewardOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dprId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).dataProductId) {
      throw new ValidationError("dataProductId is required");
    }
    const dataproductId = (input as any).dataProductId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.dataProduct.updateDataProductSteward({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as UpdateDataProductStewardOutput;
  }
}
