/**
 * ExecuteListDataProductSilos - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDataProductSilos Use Case
 *
 * DDD: Application use case for list Silo.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDataProductSilosInput, ListDataProductSilosOutput } from "../dto/silo.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { SiloRepository } from "../ports";

export class ExecuteListDataProductSilos {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly silo: SiloRepository
  ) {}

  async execute(input: ListDataProductSilosInput): Promise<ListDataProductSilosOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dprId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.silo.listDataProductSilos({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDataProductSilosOutput;
  }
}
