/**
 * ExecuteCreateDataProduct - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateDataProduct Use Case
 *
 * DDD: Application use case for create DataProduct.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateDataProductInput, CreateDataProductOutput } from "../dto/data-product.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { DataProductRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateDataProduct {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataProduct: DataProductRepository
  ) {}

  async execute(input: CreateDataProductInput): Promise<CreateDataProductOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.dprId();

    // All field names extracted from OpenAPI spec: description, name, piiClassification, stewardId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.stewardId) {
      throw new ValidationError("stewardId is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (data-products domain)
    const entityId = this.idGenerator.dprId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.dataProduct.createDataProduct({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateDataProductOutput;
  }
}
