/**
 * Readiness DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: readiness
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Readiness DTOs
 *
 * DDD: Application DTOs for Readiness use cases.
 */

import type { GetReadinessScoreParams, RecomputeReadinessParams } from "@unifora/core/readiness/types";

export type GetReadinessScoreInput = GetReadinessScoreParams;

export type RecomputeReadinessInput = RecomputeReadinessParams;

export type GetReadinessScoreOutput = {};

export type RecomputeReadinessOutput = {};
