/**
 * Routes for ProgrammePulse
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getProgrammePulse } from "../handlers/programme-pulse.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function programmePulseRoutes(fastify: FastifyInstance) {
  // GET /v1/use-cases/programme-pulse (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/use-cases/programme-pulse",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUseCasesDependenciesForRequest();
        await getProgrammePulse(request, reply, deps);
      });
    }
  );


}
