/**
 * Routes for TtvGate
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { setTTVGate } from "../handlers/ttv-gate.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function ttvGateRoutes(fastify: FastifyInstance) {
  // PUT /v1/use-cases/{useCaseId}/ttv-gates (unscoped; scope set for security middleware)
  fastify.put(
    "/v1/use-cases/:useCaseId/ttv-gates",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { useCaseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getUseCasesDependenciesForRequest();
        await setTTVGate(request, reply, deps);
      });
    }
  );


}
