/**
 * Factories barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Factories Barrel Export
 *
 * Exports all entity and DTO factories for the use-cases domain.
 * Use these factories in tests to create test data.
 */

export { createProgrammePulse } from "./programme-pulse/entity/programme-pulse.entity.factory.js";
export { createUseCase } from "./use-case/entity/use-case.entity.factory.js";
