/**
 * Handlers for Escalation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escalations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EscalationsDomainModule } from "../dependencies/escalations-ddd.dependencies.js";
import type { ListEscalationsInput, OpenEscalationInput } from "@unifora/services/escalations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/escalations
 * Operation: listEscalations
 */
export async function listEscalations(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { status?: string | string[], cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: EscalationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListEscalationsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.escalations.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/escalations
 * Operation: openEscalation
 */
export async function openEscalation(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: EscalationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: OpenEscalationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.escalations.get.execute(input);
  return reply.code(201).send(result);
}


