/**
 * Handlers for Resolve
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escalations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { EscalationsDomainModule } from "../dependencies/escalations-ddd.dependencies.js";
import type { ResolveEscalationInput } from "@unifora/services/escalations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/escalations/{escalationId}/resolve
 * Operation: resolveEscalation
 */
export async function resolveEscalation(
  request: FastifyRequest<{ Params: { escalationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: EscalationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ResolveEscalationInput = {
    escalationId: request.params.escalationId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.resolves.get.execute(input);
  return reply.code(200).send(result);
}


