/**
 * ProgrammePulseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProgrammePulseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProgrammePulseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProgrammePulseRepository,
} from "@unifora/services/use-cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProgrammePulseRepositoryDdb } from "./programme-pulse-repository.ddb.js";

/**
 * ProgrammePulseRepositoryAdapter
 *
 * Implements ProgrammePulseRepository port for infrastructure layer.
 */
export class ProgrammePulseRepositoryAdapter implements ProgrammePulseRepository {
  private readonly ddb: ProgrammePulseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProgrammePulseRepositoryDdb(this.dynamoClient);
  }

  async getProgrammePulse(input: Parameters<ProgrammePulseRepository['getProgrammePulse']>[0]): Promise<Awaited<ReturnType<ProgrammePulseRepository['getProgrammePulse']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getProgrammePulse(input);
  }
}
