/**
 * TtvGateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TtvGateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements TtvGateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  TtvGateRepository,
} from "@unifora/services/use-cases";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { TtvGateRepositoryDdb } from "./ttv-gate-repository.ddb.js";

/**
 * TtvGateRepositoryAdapter
 *
 * Implements TtvGateRepository port for infrastructure layer.
 */
export class TtvGateRepositoryAdapter implements TtvGateRepository {
  private readonly ddb: TtvGateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new TtvGateRepositoryDdb(this.dynamoClient);
  }

  async setTTVGate(input: Parameters<TtvGateRepository['setTTVGate']>[0]): Promise<Awaited<ReturnType<TtvGateRepository['setTTVGate']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.setTTVGate(input);
  }
}
