/**
 * ExecuteGetProgrammePulse - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetProgrammePulse Use Case
 *
 * DDD: Application use case for get ProgrammePulse.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetProgrammePulseInput, GetProgrammePulseOutput } from "../dto/programme-pulse.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { ProgrammePulseRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetProgrammePulse {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly programmePulse: ProgrammePulseRepository
  ) {}

  async execute(input: GetProgrammePulseInput): Promise<GetProgrammePulseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ucsId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.programmePulse.getProgrammePulse({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetProgrammePulseOutput;
  }
}
