/**
 * ExecuteCreateUseCase - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateUseCase Use Case
 *
 * DDD: Application use case for create UseCase.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateUseCaseInput, CreateUseCaseOutput } from "../dto/use-case.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { UseCaseRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateUseCase {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly useCase: UseCaseRepository
  ) {}

  async execute(input: CreateUseCaseInput): Promise<CreateUseCaseOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ucsId();

    // All field names extracted from OpenAPI spec: domain, name, sponsor
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (use-cases domain)
    const entityId = this.idGenerator.ucsId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.useCase.createUseCase({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateUseCaseOutput;
  }
}
