/**
 * ExecuteSetTTVGate - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSetTTVGate Use Case
 *
 * DDD: Application use case for update TtvGate.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SetTTVGateInput, SetTTVGateOutput } from "../dto/ttv-gate.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { TtvGateRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanUpdate } from "../policies/can-update.policy";
export class ExecuteSetTTVGate {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ttvGate: TtvGateRepository
  ) {}

  async execute(input: SetTTVGateInput): Promise<SetTTVGateOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ucsId();

    // All field names extracted from OpenAPI spec
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).useCaseId) {
      throw new ValidationError("useCaseId is required");
    }
    const usecaseId = (input as any).useCaseId;
    // No get/list operation for this resource - call update directly
    // Check policy
    if (!CanUpdate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Update entity via repository (pass correlation ID for response meta)
    const updated = await this.ttvGate.setTTVGate({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return updated as SetTTVGateOutput;
  }
}
