/**
 * ExecuteLinkDataProduct - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteLinkDataProduct Use Case
 *
 * DDD: Application use case for get DataProduct.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { LinkDataProductInput, LinkDataProductOutput } from "../dto/data-product.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { DataProductRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteLinkDataProduct {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataProduct: DataProductRepository
  ) {}

  async execute(input: LinkDataProductInput): Promise<LinkDataProductOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ucsId();

    // All field names extracted from OpenAPI spec: dataProductId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).useCaseId) {
      throw new ValidationError("useCaseId is required");
    }
    const usecaseId = (input as any).useCaseId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.dataProduct.linkDataProduct({ useCaseId: usecaseId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${usecaseId}`);
    }

    return entity as LinkDataProductOutput;
  }
}
