/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Capacity Domain Use Cases
 * 
 * List of all use case names for the capacity domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CAPACITY_USE_CASES = [
  "executeCreateCapacityPlan",
  "executeListCapacityConflicts",
  "executeListCapacityPlans"
] as const;
