/**
 * DataProduct DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataProduct DTOs
 *
 * DDD: Application DTOs for DataProduct use cases.
 */

import type { LinkDataProductParams, LinkDataProductRequestInput } from "@unifora/core/use-cases/types";

export type LinkDataProductInput = LinkDataProductParams & LinkDataProductRequestInput;

export type LinkDataProductOutput = {};
