/**
 * ProgrammePulse DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProgrammePulse DTOs
 *
 * DDD: Application DTOs for ProgrammePulse use cases.
 */

export type GetProgrammePulseInput = {};

export type GetProgrammePulseOutput = {};
