/**
 * TtvGate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TtvGate DTOs
 *
 * DDD: Application DTOs for TtvGate use cases.
 */

import type { SetTTVGateParams, SetTTVGateRequestInput } from "@unifora/core/use-cases/types";

export type SetTTVGateInput = SetTTVGateParams & SetTTVGateRequestInput;

export type SetTTVGateOutput = {};
