/**
 * Handlers for Lineage
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LineageDomainModule } from "../dependencies/lineage-ddd.dependencies.js";
import type { GetLineageInput } from "@unifora/services/lineage";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/lineage/{dataProductId}
 * Operation: getLineage
 */
export async function getLineage(
  request: FastifyRequest<{ Params: { dataProductId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LineageDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLineageInput = {
    dataProductId: request.params.dataProductId,
  };
  const result = await deps.useCases.lineages.get.execute(input);
  return reply.code(200).send(result);
}


