/**
 * Handlers for SlaEvent
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pipelines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PipelinesDomainModule } from "../dependencies/pipelines-ddd.dependencies.js";
import type { RecordPipelineSLAEventInput } from "@unifora/services/pipelines";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/pipelines/{pipelineId}/sla-events
 * Operation: recordPipelineSLAEvent
 */
export async function recordPipelineSLAEvent(
  request: FastifyRequest<{ Params: { pipelineId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PipelinesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RecordPipelineSLAEventInput = {
    pipelineId: request.params.pipelineId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.slaEvents.get.execute(input);
  return reply.code(200).send(result);
}


