/**
 * Attestation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestation DTOs
 *
 * DDD: Application DTOs for Attestation use cases.
 */

import type { UpsertPlatformAttestationRequestInput } from "@unifora/core/security-attestations/types";

export type GetPlatformAttestationInput = {};

export type UpsertPlatformAttestationInput = UpsertPlatformAttestationRequestInput;

export type GetPlatformAttestationOutput = {};

export type UpsertPlatformAttestationOutput = {};
