/**
 * Pipeline Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pipelines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { PipelineEntity } from "@unifora/core/pipelines/models/index.js";
import { pipelinesSchemas } from "@unifora/core/pipelines";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "pip";

export function createPipeline(overrides: Partial<PipelineEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    name: overrides.name ?? faker.person.fullName(),
    owner: overrides.owner ?? faker.lorem.word(),
    pipelineId: overrides.pipelineId ?? `pip_${ulid().toLowerCase()}`,
    status: overrides.status ?? "registered",
    ...overrides,
  };

  return pipelinesSchemas.Pipeline.parse(raw);
}

export function pipelineBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createPipeline(overrides));
}
