/**
 * ExecuteUpsertPlatformAttestation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertPlatformAttestation Use Case
 *
 * DDD: Application use case for get Attestation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertPlatformAttestationInput, UpsertPlatformAttestationOutput } from "../dto/attestation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { AttestationRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteUpsertPlatformAttestation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly attestation: AttestationRepository
  ) {}

  async execute(input: UpsertPlatformAttestationInput): Promise<UpsertPlatformAttestationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.secId();

    // All field names extracted from OpenAPI spec: cloudOwnershipAcknowledged, controlsChecklist
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.attestation.upsertPlatformAttestation({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as UpsertPlatformAttestationOutput;
  }
}
