/**
 * ExecuteListPipelines - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pipelines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPipelines Use Case
 *
 * DDD: Application use case for list Pipeline.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPipelinesInput, ListPipelinesOutput } from "../dto/pipeline.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { PipelineRepository } from "../ports";

export class ExecuteListPipelines {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pipeline: PipelineRepository
  ) {}

  async execute(input: ListPipelinesInput): Promise<ListPipelinesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pipId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.pipeline.listPipelines({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPipelinesOutput;
  }
}
