/**
 * ExecuteRegisterPipeline - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pipelines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterPipeline Use Case
 *
 * DDD: Application use case for create Pipeline.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterPipelineInput, RegisterPipelineOutput } from "../dto/pipeline.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { PipelineRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterPipeline {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pipeline: PipelineRepository
  ) {}

  async execute(input: RegisterPipelineInput): Promise<RegisterPipelineOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.pipId();

    // All field names extracted from OpenAPI spec: name, owner, sla, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.owner) {
      throw new ValidationError("owner is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (pipelines domain)
    const entityId = this.idGenerator.pipId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.pipeline.registerPipeline({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterPipelineOutput;
  }
}
