/**
 * GetUseCase handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getUseCase } from "@unifora/api-server/domains/use-cases/handlers";
import type { UseCasesDDDDependencies } from "@unifora/api-server/domains/use-cases";
import { createUseCase as createUseCaseEntity } from "@unifora/factories/use-cases";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@unifora/tests/shared";
import { USECASES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetUseCase", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: UseCasesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<UseCasesDDDDependencies>(
      USECASES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createUseCaseEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetUseCase, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { useCaseId: entity.id };

    await getUseCase(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetUseCase.execute).toHaveBeenCalledWith(expect.objectContaining({ useCaseId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { useCaseId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetUseCase, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getUseCase(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
