/**
 * LineageRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: lineage
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LineageRepository Port
 *
 * DDD: Application port for lineagerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLineageInput, GetLineageOutput } from "../dto/lineage.dto";
export interface LineageRepository {
  getLineage(input: GetLineageInput): Promise<GetLineageOutput>;
}

export type { GetLineageInput, GetLineageOutput } from "../dto/lineage.dto";
