/**
 * Shares DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Shares Domain Module - Composition root
 *
 * DDD: Composition root for shares domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DecideRepositoryAdapter,
  ShareRepositoryAdapter,
} from "@unifora/adapters/shares";
import { getIdGeneratorService } from "@unifora/adapters";
import type { AdapterDynamoDBClient } from "@unifora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateShareRequest,
  ExecuteDecideShareRequest,
  ExecuteListShareRequests,
} from "@unifora/services/shares/usecases";
// Ports (interfaces)
import type {
  DecideRepository,
  ShareRepository,
} from "@unifora/services/shares/ports";

export interface SharesDomainModule {
  repos: {
    decides: DecideRepository;
    shares: ShareRepository;
  };
  useCases: {
    decides: {
      get: ExecuteDecideShareRequest;
    };
    shares: {
      create: ExecuteCreateShareRequest;
      list: ExecuteListShareRequests;
    };
  };
}

export function buildSharesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): SharesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      decides?: DecideRepository;
      shares?: ShareRepository;
    } = {};

    obj.decides = new DecideRepositoryAdapter(dynamoClient);
    obj.shares = new ShareRepositoryAdapter(dynamoClient);
    return {
      decides: obj.decides!,
      shares: obj.shares!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    decides: {
      get: new ExecuteDecideShareRequest(executionContext, idGenerator, repos.decides),
    },
    shares: {
      create: new ExecuteCreateShareRequest(executionContext, idGenerator, repos.shares),
      list: new ExecuteListShareRequests(executionContext, idGenerator, repos.shares),
    },
  };
  return { repos, useCases: useCases as SharesDomainModule["useCases"] };
}
