/**
 * Handlers for Attestation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: security-attestations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { SecurityAttestationsDomainModule } from "../dependencies/security-attestations-ddd.dependencies.js";
import type { GetPlatformAttestationInput, UpsertPlatformAttestationInput } from "@unifora/services/security-attestations";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/security/attestation
 * Operation: getPlatformAttestation
 */
export async function getPlatformAttestation(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SecurityAttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetPlatformAttestationInput = {};
  const result = await deps.useCases.attestations.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PUT /v1/security/attestation
 * Operation: upsertPlatformAttestation
 */
export async function upsertPlatformAttestation(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: SecurityAttestationsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpsertPlatformAttestationInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.attestations.get.execute(input);
  return reply.code(200).send(result);
}


