/**
 * UseCase Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { UseCaseEntity } from "@unifora/core/use-cases/models/index.js";
import { useCasesSchemas } from "@unifora/core/use-cases";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ucs";

export function createUseCase(overrides: Partial<UseCaseEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    linkedDataProductIds: overrides.linkedDataProductIds ?? [],
    name: overrides.name ?? faker.person.fullName(),
    status: overrides.status ?? "proposed",
    useCaseId: overrides.useCaseId ?? `ucs_${ulid().toLowerCase()}`,
    ...overrides,
  };

  return useCasesSchemas.UseCase.parse(raw);
}

export function useCaseBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createUseCase(overrides));
}
