/**
 * ConflictRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConflictRepository Port
 *
 * DDD: Application port for conflictrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListCapacityConflictsInput, ListCapacityConflictsOutput } from "../dto/conflict.dto";
export interface ConflictRepository {
  listCapacityConflicts(input: ListCapacityConflictsInput): Promise<ListCapacityConflictsOutput>;
}

export type { ListCapacityConflictsInput, ListCapacityConflictsOutput } from "../dto/conflict.dto";
