/**
 * PlanRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PlanRepository Port
 *
 * DDD: Application port for planrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCapacityPlanInput, CreateCapacityPlanOutput, ListCapacityPlansInput, ListCapacityPlansOutput } from "../dto/plan.dto";
export interface PlanRepository {
  listCapacityPlans(input: ListCapacityPlansInput): Promise<ListCapacityPlansOutput>;
  createCapacityPlan(input: CreateCapacityPlanInput): Promise<CreateCapacityPlanOutput>;
}

export type { CreateCapacityPlanInput, CreateCapacityPlanOutput, ListCapacityPlansInput, ListCapacityPlansOutput } from "../dto/plan.dto";
