/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escalations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./list-escalations.handler.test.js";
export * from "./open-escalation.handler.test.js";
