/**
 * OpenEscalation handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escalations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { openEscalation } from "@unifora/api-server/domains/escalations/handlers";
import type { EscalationsDDDDependencies } from "@unifora/api-server/domains/escalations";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@unifora/tests/shared";
import { ESCALATIONS_USE_CASES } from "../__factories__/use-cases.js";

describe("OpenEscalation", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: EscalationsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<EscalationsDDDDependencies>(
      ESCALATIONS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeOpenEscalation, "execute").mockResolvedValue(useCaseResult);

    await openEscalation(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeOpenEscalation.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
