/**
 * Pipelines DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pipelines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pipelines Domain Module - Composition root
 *
 * DDD: Composition root for pipelines domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  PipelineRepositoryAdapter,
  SlaEventRepositoryAdapter,
} from "@unifora/adapters/pipelines";
import { getIdGeneratorService } from "@unifora/adapters";
import type { AdapterDynamoDBClient } from "@unifora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetPipeline,
  ExecuteListPipelines,
  ExecuteRecordPipelineSLAEvent,
  ExecuteRegisterPipeline,
} from "@unifora/services/pipelines/usecases";
// Ports (interfaces)
import type {
  PipelineRepository,
  SlaEventRepository,
} from "@unifora/services/pipelines/ports";

export interface PipelinesDomainModule {
  repos: {
    pipelines: PipelineRepository;
    slaEvents: SlaEventRepository;
  };
  useCases: {
    pipelines: {
      create: ExecuteRegisterPipeline;
      get: ExecuteGetPipeline;
      list: ExecuteListPipelines;
    };
    slaEvents: {
      get: ExecuteRecordPipelineSLAEvent;
    };
  };
}

export function buildPipelinesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PipelinesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      pipelines?: PipelineRepository;
      slaEvents?: SlaEventRepository;
    } = {};

    obj.pipelines = new PipelineRepositoryAdapter(dynamoClient);
    obj.slaEvents = new SlaEventRepositoryAdapter(dynamoClient);
    return {
      pipelines: obj.pipelines!,
      slaEvents: obj.slaEvents!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    pipelines: {
      create: new ExecuteRegisterPipeline(executionContext, idGenerator, repos.pipelines),
      get: new ExecuteGetPipeline(executionContext, idGenerator, repos.pipelines),
      list: new ExecuteListPipelines(executionContext, idGenerator, repos.pipelines),
    },
    slaEvents: {
      get: new ExecuteRecordPipelineSLAEvent(executionContext, idGenerator, repos.slaEvents),
    },
  };
  return { repos, useCases: useCases as PipelinesDomainModule["useCases"] };
}
