/**
 * GetAuditExport handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getAuditExport } from "@unifora/api-server/domains/audits/handlers";
import type { AuditsDDDDependencies } from "@unifora/api-server/domains/audits";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@unifora/tests/shared";
import { AUDITS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetAuditExport", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: AuditsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<AuditsDDDDependencies>(
      AUDITS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetAuditExport, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { auditExportId: entity.id };

    await getAuditExport(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetAuditExport.execute).toHaveBeenCalledWith(expect.objectContaining({ auditExportId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { auditExportId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetAuditExport, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getAuditExport(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
