/**
 * ExecuteGetAuditExport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetAuditExport Use Case
 *
 * DDD: Application use case for get Export.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetAuditExportInput, GetAuditExportOutput } from "../dto/export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { ExportRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetAuditExport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportRepo: ExportRepository
  ) {}

  async execute(input: GetAuditExportInput): Promise<GetAuditExportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.audId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).auditExportId) {
      throw new ValidationError("auditExportId is required");
    }
    const auditexportId = (input as any).auditExportId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.exportRepo.getAuditExport({ auditExportId: auditexportId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${auditexportId}`);
    }

    return entity as GetAuditExportOutput;
  }
}
