/**
 * DataProductRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataProductRepository Port
 *
 * DDD: Application port for dataproductrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { LinkDataProductInput, LinkDataProductOutput } from "../dto/data-product.dto";
export interface DataProductRepository {
  linkDataProduct(input: LinkDataProductInput): Promise<LinkDataProductOutput>;
}

export type { LinkDataProductInput, LinkDataProductOutput } from "../dto/data-product.dto";
