/**
 * ProgrammePulseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProgrammePulseRepository Port
 *
 * DDD: Application port for programmepulserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetProgrammePulseInput, GetProgrammePulseOutput } from "../dto/programme-pulse.dto";
export interface ProgrammePulseRepository {
  getProgrammePulse(input: GetProgrammePulseInput): Promise<GetProgrammePulseOutput>;
}

export type { GetProgrammePulseInput, GetProgrammePulseOutput } from "../dto/programme-pulse.dto";
