/**
 * UseCaseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * UseCaseRepository Port
 *
 * DDD: Application port for usecaserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateUseCaseInput, CreateUseCaseOutput, GetUseCaseInput, GetUseCaseOutput, ListUseCasesInput, ListUseCasesOutput } from "../dto/use-case.dto";
export interface UseCaseRepository {
  listUseCases(input: ListUseCasesInput): Promise<ListUseCasesOutput>;
  createUseCase(input: CreateUseCaseInput): Promise<CreateUseCaseOutput>;
  getUseCase(input: GetUseCaseInput): Promise<GetUseCaseOutput>;
}

export type { CreateUseCaseInput, CreateUseCaseOutput, GetUseCaseInput, GetUseCaseOutput, ListUseCasesInput, ListUseCasesOutput } from "../dto/use-case.dto";
