/**
 * EscalationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escalations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EscalationRepository Port
 *
 * DDD: Application port for escalationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListEscalationsInput, ListEscalationsOutput, OpenEscalationInput, OpenEscalationOutput } from "../dto/escalation.dto";
export interface EscalationRepository {
  listEscalations(input: ListEscalationsInput): Promise<ListEscalationsOutput>;
  openEscalation(input: OpenEscalationInput): Promise<OpenEscalationOutput>;
}

export type { ListEscalationsInput, ListEscalationsOutput, OpenEscalationInput, OpenEscalationOutput } from "../dto/escalation.dto";
