/**
 * Plan DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Plan DTOs
 *
 * DDD: Application DTOs for Plan use cases.
 */

import type { CreateCapacityPlanRequestInput, ListCapacityPlansParams } from "@unifora/core/capacity/types";

export type ListCapacityPlansInput = ListCapacityPlansParams;

export type CreateCapacityPlanInput = CreateCapacityPlanRequestInput;

export type ListCapacityPlansOutput = {};

export type CreateCapacityPlanOutput = {};
