/**
 * DataProductRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataProductRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataProductRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataProductRepository,
} from "@unifora/services/data-products";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataProductRepositoryDdb } from "./data-product-repository.ddb.js";

/**
 * DataProductRepositoryAdapter
 *
 * Implements DataProductRepository port for infrastructure layer.
 */
export class DataProductRepositoryAdapter implements DataProductRepository {
  private readonly ddb: DataProductRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataProductRepositoryDdb(this.dynamoClient);
  }

  async listDataProducts(input: Parameters<DataProductRepository['listDataProducts']>[0]): Promise<Awaited<ReturnType<DataProductRepository['listDataProducts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataProducts(input);
  }

  async createDataProduct(input: Parameters<DataProductRepository['createDataProduct']>[0]): Promise<Awaited<ReturnType<DataProductRepository['createDataProduct']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDataProduct(input);
  }

  async getDataProduct(input: Parameters<DataProductRepository['getDataProduct']>[0]): Promise<Awaited<ReturnType<DataProductRepository['getDataProduct']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDataProduct(input);
  }

  async updateDataProductSteward(input: Parameters<DataProductRepository['updateDataProductSteward']>[0]): Promise<Awaited<ReturnType<DataProductRepository['updateDataProductSteward']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateDataProductSteward(input);
  }
}
