/**
 * SiloRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SiloRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SiloRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SiloRepository,
} from "@unifora/services/data-products";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SiloRepositoryDdb } from "./silo-repository.ddb.js";

/**
 * SiloRepositoryAdapter
 *
 * Implements SiloRepository port for infrastructure layer.
 */
export class SiloRepositoryAdapter implements SiloRepository {
  private readonly ddb: SiloRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SiloRepositoryDdb(this.dynamoClient);
  }

  async listDataProductSilos(input: Parameters<SiloRepository['listDataProductSilos']>[0]): Promise<Awaited<ReturnType<SiloRepository['listDataProductSilos']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataProductSilos(input);
  }
}
