/**
 * ExecuteOpenEscalation - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: escalations
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteOpenEscalation Use Case
 *
 * DDD: Application use case for get Escalation.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { OpenEscalationInput, OpenEscalationOutput } from "../dto/escalation.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { EscalationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteOpenEscalation {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly escalation: EscalationRepository
  ) {}

  async execute(input: OpenEscalationInput): Promise<OpenEscalationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.escId();

    // All field names extracted from OpenAPI spec: deadlineAt, reason, shareRequestId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).shareRequestId) {
      throw new ValidationError("shareRequestId is required");
    }
    const sharerequestId = (input as any).shareRequestId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.escalation.openEscalation({ shareRequestId: sharerequestId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${sharerequestId}`);
    }

    return entity as OpenEscalationOutput;
  }
}
