/**
 * ConflictRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ConflictRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ConflictRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ConflictRepository,
} from "@unifora/services/capacity";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ConflictRepositoryDdb } from "./conflict-repository.ddb.js";

/**
 * ConflictRepositoryAdapter
 *
 * Implements ConflictRepository port for infrastructure layer.
 */
export class ConflictRepositoryAdapter implements ConflictRepository {
  private readonly ddb: ConflictRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ConflictRepositoryDdb(this.dynamoClient);
  }

  async listCapacityConflicts(input: Parameters<ConflictRepository['listCapacityConflicts']>[0]): Promise<Awaited<ReturnType<ConflictRepository['listCapacityConflicts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCapacityConflicts(input);
  }
}
