/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: use-cases
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * UseCases Domain Use Cases
 * 
 * List of all use case names for the use-cases domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const USECASES_USE_CASES = [
  "executeCreateUseCase",
  "executeGetProgrammePulse",
  "executeGetUseCase",
  "executeLinkDataProduct",
  "executeListUseCases",
  "executeSetTTVGate"
] as const;
