/**
 * Capacity DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: capacity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Capacity Domain Module - Composition root
 *
 * DDD: Composition root for capacity domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ConflictRepositoryAdapter,
  PlanRepositoryAdapter,
} from "@unifora/adapters/capacity";
import { getIdGeneratorService } from "@unifora/adapters";
import type { AdapterDynamoDBClient } from "@unifora/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCapacityPlan,
  ExecuteListCapacityConflicts,
  ExecuteListCapacityPlans,
} from "@unifora/services/capacity/usecases";
// Ports (interfaces)
import type {
  ConflictRepository,
  PlanRepository,
} from "@unifora/services/capacity/ports";

export interface CapacityDomainModule {
  repos: {
    conflicts: ConflictRepository;
    plans: PlanRepository;
  };
  useCases: {
    conflicts: {
      list: ExecuteListCapacityConflicts;
    };
    plans: {
      create: ExecuteCreateCapacityPlan;
      list: ExecuteListCapacityPlans;
    };
  };
}

export function buildCapacityDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): CapacityDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      conflicts?: ConflictRepository;
      plans?: PlanRepository;
    } = {};

    obj.conflicts = new ConflictRepositoryAdapter(dynamoClient);
    obj.plans = new PlanRepositoryAdapter(dynamoClient);
    return {
      conflicts: obj.conflicts!,
      plans: obj.plans!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    conflicts: {
      list: new ExecuteListCapacityConflicts(executionContext, idGenerator, repos.conflicts),
    },
    plans: {
      create: new ExecuteCreateCapacityPlan(executionContext, idGenerator, repos.plans),
      list: new ExecuteListCapacityPlans(executionContext, idGenerator, repos.plans),
    },
  };
  return { repos, useCases: useCases as CapacityDomainModule["useCases"] };
}
