/**
 * Handlers for Export
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: audits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { AuditsDomainModule } from "../dependencies/audits-ddd.dependencies.js";
import type { CreateUniforaAuditExportInput, GetAuditExportInput } from "@unifora/services/audits";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/audits/exports
 * Operation: createUniforaAuditExport
 */
export async function createUniforaAuditExport(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: AuditsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateUniforaAuditExportInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exports.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/audits/exports/{auditExportId}
 * Operation: getAuditExport
 */
export async function getAuditExport(
  request: FastifyRequest<{ Params: { auditExportId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: AuditsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetAuditExportInput = {
    auditExportId: request.params.auditExportId,
  };
  const result = await deps.useCases.exports.get.execute(input);
  return reply.code(200).send(result);
}


