/**
 * ExecuteCreateShareRequest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateShareRequest Use Case
 *
 * DDD: Application use case for create Share.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateShareRequestInput, CreateShareRequestOutput } from "../dto/share.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { ShareRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateShareRequest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly share: ShareRepository
  ) {}

  async execute(input: CreateShareRequestInput): Promise<CreateShareRequestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.shrId();

    // All field names extracted from OpenAPI spec: consentMinimisationSatisfied, dataProductId, escalateAfterAt, purpose, shareScope, useCaseId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.dataProductId) {
      throw new ValidationError("dataProductId is required");
    }
    if (!input.shareScope) {
      throw new ValidationError("shareScope is required");
    }
    if (!input.purpose) {
      throw new ValidationError("purpose is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (shares domain)
    const entityId = this.idGenerator.shrId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.share.createShareRequest({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateShareRequestOutput;
  }
}
