/**
 * ExecuteListShareRequests - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: shares
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListShareRequests Use Case
 *
 * DDD: Application use case for list Share.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListShareRequestsInput, ListShareRequestsOutput } from "../dto/share.dto";
import type { ExecutionContextService, IdGeneratorService } from "@unifora/services/_shared/index.js";
import type { ShareRepository } from "../ports";

export class ExecuteListShareRequests {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly share: ShareRepository
  ) {}

  async execute(input: ListShareRequestsInput): Promise<ListShareRequestsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.shrId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.share.listShareRequests({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListShareRequestsOutput;
  }
}
