/**
 * Pipeline Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pipelines
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/pipelines.openapi.types.js";
import { schemas } from "../schemas/pipelines.schemas.js";

/**
 * Entity: PipelineEntity
 * Description: Represents the Pipeline domain model.
 * Source: schemas.Pipeline
 * Type: Domain Entity (API)
 */
export const PipelineEntitySchema = schemas.Pipeline;
export type PipelineEntity = components["schemas"]["Pipeline"];
