/**
 * Routes for Silo
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: data-products
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listDataProductSilos } from "../handlers/silo.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function siloRoutes(fastify: FastifyInstance) {
  // GET /v1/data-products/{dataProductId}/silos (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-products/:dataProductId/silos",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { dataProductId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getDataProductsDependenciesForRequest();
        await listDataProductSilos(request, reply, deps);
      });
    }
  );


}
